Repository siliconflow/onediff, pull requests merged in 2024-03, with the labels that each got.

#718 SD-WebUI supports offline quantized model
  README_ENTERPRISE.md
  onediff_diffusers_extensions/tools/quantization/quantize-sd-fast.py
  onediff_sd_webui_extensions/scripts/onediff.py
  onediff_sd_webui_extensions/tools/convert_diffusers_to_sd.py
  onediff_sd_webui_extensions/tools/convert_diffusers_to_sdxl.py
Labels: Response-urgent_and_important

#751 import torch first
  onediff_diffusers_extensions/examples/experimental/text_to_image_sdxl_torch_compile.py
  onediff_diffusers_extensions/examples/image_to_image.py
  onediff_diffusers_extensions/examples/text_to_image.py
  onediff_diffusers_extensions/examples/text_to_image_sdxl.py
  onediff_diffusers_extensions/examples/text_to_image_sdxl_mp_load.py
  onediff_diffusers_extensions/examples/text_to_image_sdxl_save_load.py
  onediff_diffusers_extensions/examples/text_to_image_sdxl_turbo.py
  onediff_diffusers_extensions/examples/unet_torch_interplay.py
Labels: Request-bug

#575 support ComfyUI-AnimateDiff-Evolved
  onediff_comfy_nodes/__init__.py
  onediff_comfy_nodes/_config.py
  onediff_comfy_nodes/_nodes.py
  onediff_comfy_nodes/infer_compiler_registry/register_comfy/__init__.py
  onediff_comfy_nodes/modules/hijack_animatediff/README.md
  onediff_comfy_nodes/modules/hijack_animatediff/__init__.py
  onediff_comfy_nodes/modules/hijack_animatediff/_config.py
  onediff_comfy_nodes/modules/hijack_animatediff/motion_module_ad.py
  onediff_comfy_nodes/modules/hijack_animatediff/sampling.py
  onediff_comfy_nodes/modules/hijack_animatediff/utils_motion.py
  onediff_comfy_nodes/modules/hijack_samplers.py
  src/onediff/infer_compiler/import_tools/__init__.py
  src/onediff/infer_compiler/import_tools/dyn_mock_mod.py
  src/onediff/infer_compiler/import_tools/import_module_utils.py
  src/onediff/infer_compiler/import_tools/importer.py
  src/onediff/infer_compiler/transform/builtin_transform.py
  src/onediff/infer_compiler/utils/graph_management_utils.py
  src/onediff/infer_compiler/utils/log_utils.py
  src/onediff/infer_compiler/utils/module_operations.py
  src/onediff/infer_compiler/utils/patch_for_compiler.py
  src/onediff/infer_compiler/with_oneflow_compile.py
  src/onediff/optimization/quant_optimizer.py
Labels: Request-new_feature, Response-urgent_and_important, Response-important
